### ISSUE TITLE
add a user table and authentication

### ISSUE THREAD

**Issue by bbelderbos** [felipe74590/atx-events#21]
Roles: admin, regular user (can be boolean flag on that model/table)

For auth we can use this: https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/?h=jwt

**Comment by felipe74590** [comment]
```
Users |  
-- | --
user_name | str
Password | str
events_saved | list
events_attended | list
Disabled | boolean  
```

**Comment by bbelderbos** [comment]
repo where I used fastapi auth: 

https://github.com/bbelderbos/codeimag.es

**Comment by bbelderbos** [comment]
user - event would be many to many (user can save or attend many events, and an event can be saved/ attended by many users) so you'd need an association table, see https://sqlmodel.tiangolo.com/tutorial/many-to-many/#link-primary-key

**Comment by bbelderbos** [comment]
will be something like this:

https://sqlmodel.tiangolo.com/tutorial/many-to-many/create-models-with-link/#team-model

<img width="810" alt="image" src="https://github.com/user-attachments/assets/37494435-003f-42bd-b6d9-f53edf697429">
