### ISSUE TITLE
deployment

### ISSUE THREAD

**Issue by bbelderbos** [felipe74590/atx-events#24]
For in a week or so: 

- check cloud providers and pick one
- deploy this app
- have fastapi running, db created, scrapers to run each day using a scheduled task or cronjob utility (depends vendor)

**Comment by bbelderbos** [comment]
@felipe74590 ok, it is indeed pretty simple, only hit a thing with the env variable, heroku = postgres, app wants postgresql, see here: https://github.com/PyBites-Open-Source/affirmations-api/blob/main/heroku.md

HTH
Bob

**Comment by felipe74590** [comment]
Was able to create app and test deployments, ran into the heroku/postgres issue and used the example work around provided to solve that. Currently running into a dependency issue that I will look further into. EDIT: NVM, looks like I have the dependency set in my dev-dependencies and requirements only has dependencies.
```
remote:     dbapi = dbapi_meth(**dbapi_args)
remote:             ^^^^^^^^^^^^^^^^^^^^^^^^
remote:   File "/app/.heroku/python/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 690, in import_dbapi
remote:     import psycopg2
remote: ModuleNotFoundError: No module named 'psycopg2'
remote: Waiting for release... failed.
To https://git.heroku.com/atx-events-api.git
   ecbe50f..2d15299  main -> main
```

**Comment by bbelderbos** [comment]
yep, before seeing this I already logged an issue for this: https://github.com/felipe74590/atx-events/issues/39
