### ISSUE TITLE
database migrations

### ISSUE THREAD

**Issue by bbelderbos** [felipe74590/atx-events#25]
Now when you make table changes you might have to squash your database, that is not too scalable / maintainable.

You'd typically use a db migration system, for sqlmodel/SQLAlchemy that would typically be Alembic, here is an intro video:

Database migrations matter! Get up and running with Alembic + sqlmodel
https://www.youtube.com/watch?v=gekC1ESLxPs

**Comment by felipe74590** [comment]
So I followed the tutorial and I see how this migrates the tables in my data base using the Event model but it doesn't migrate the data. So I created a function to migrate the data from the sqlite db "atx_events.db" but when i checked my postgrsql database  "atx-events" .  One question would be do I start using my postgreSQL databse URL in the function that originally moved added my events
```➜  atx-events git:(building_api) ✗ psql -U felipecontreras -d atx-events
psql (14.13 (Homebrew))
Type "help" for help.

atx-events=# select * from event;
 id | title | venue | start_datetime | category | event_link
----+-------+-------+----------------+----------+------------
(0 rows)

atx-events=#```

**Comment by bbelderbos** [comment]
Yeah a migration tool like Alembic only takes care of the schema, if you want to port over any data, you'd have to write a script for that. 

In this case it doesn't matter, right? Just run the scrapers again and you'll have new data.

Yes, let's use postgres from here on, you can set it in .env, something like:

```
DATABASE_URL=postgres://postgres:password@0.0.0.0:5432/your-db
```

**Comment by felipe74590** [comment]
Added associative tables, ran `uv run alembic upgrade head` in to the following error . Will try to troubleshoot further tomorrow.
 ``` 
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table "user" because other objects depend on it
DETAIL:  constraint usereventssaved_user_id_fkey on table usereventssaved depends on table "user"
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL:
DROP TABLE "user"]
(Background on this error at: https://sqlalche.me/e/20/2j85)
```

**Comment by bbelderbos** [comment]
I get a different error using a fresh new postgres db:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) table "usereventsattended" does not exist

[SQL:
DROP TABLE usereventsattended]
```

Looks like the upgrade() and downgrade() functions have been reversed in logic?

<img width="501" alt="image" src="https://github.com/user-attachments/assets/f6b78304-bca6-47e4-8a8d-5d723ccebf2f">

Usually the drop goes in the downgrade? You have the opposite. How did this happen?

I deleted the migration files to start over but then I got empty upgrade and downgrade functions so it seems that the models are not detected.

I checked the env.py file and that seems the case because the models are not imported, fix:

<img width="969" alt="image" src="https://github.com/user-attachments/assets/4be7e4a7-6164-4542-bf12-3dec7fd3a05b">

Committed here for convenience: 6020140405bcd0c93f595a454d92516eb1d48908

Then it works (again, after removing the `migrations/versions/*` files:

```
$ uv run alembic revision --autogenerate -m "initial migration"

INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.autogenerate.compare] Detected added table 'event'
INFO  [alembic.autogenerate.compare] Detected added table 'user'
INFO  [alembic.autogenerate.compare] Detected added table 'usereventsattended'
INFO  [alembic.autogenerate.compare] Detected added table 'usereventssaved'
  Generating /Users/bbelderbos/code/pdm/felipe/atx-events/migrations/versions/17e3cda41060_initial_migration.py ...  done
```

And:

```
$ uv run alembic upgrade head
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 17e3cda41060, initial migration
```

Please pull the branch and run these two alembic commands and let me know if it works (you might need to make a new postgres db first ...)

HTH
Bob

**Comment by felipe74590** [comment]
Thanks for pointing that out, I looked at my commits from when I did the first migration and I see the Event table imported in the file but then a commit later its gone. Looks like pre-commit removed my imports this time when I made the change first. Might have to add an exception code to stop that, used --no-verify for now.
 ```
Fixed 4 errors:
- migrations/env.py:
    4 × F401 (unused-import)
```

**Comment by bbelderbos** [comment]
oh wow that is a false positive, tricky, which check was that? maybe `# noqa` works?
