### ISSUE TITLE
Streamlit UI

### ISSUE THREAD

**Issue by bbelderbos** [felipe74590/atx-events#4]
We can either go full web framework = Flask or Django, or go api-first = FastAPI, maybe the latter is more suitable for this app. Then you can use Streamlit for a quick prototype for the front-end. What do you think?

**Comment by bbelderbos** [comment]
Updated issue title to first use Streamlit to quickly prototype the front-end, we can then later swap it out for something more sophisticated.

**Comment by felipe74590** [comment]
Current todo: 
- Create events front page that loads all events in DB, and add a search bar to take in query parameters like events name, venue name, category, or dates.
- Create User page/login page
