### ISSUE TITLE
scraping improvement

### ISSUE THREAD

**Issue by bbelderbos** [felipe74590/atx-events#6]
This works for me:

```
listings = event.find_all("div", class_="ds-listing")
for listing in listings:
...
```

For the datetime this should work:

```
start_time = listing.find("meta", itemprop="startDate")
```

Let me know if you can successfully locate title, category, start_datetime, link and venue from drilling down in the `listing` div ...

**Comment by felipe74590** [comment]
Was able to clean up the listing data pull to be cleaner. The start_time worked, had to add a line to convert the start date from a string to an actual datetime class and as well as account for events with To Be Determined (TBD) start_times.

**Comment by bbelderbos** [comment]
Just saw it, great work.
